###########
# VCBungee
# General Bungee Utility for VaultCraft (August 19, 2014)
# Authors:
#  Connor Hollasch
#  Nick Peterson
###########
name: VCBungee
version: 1.0
main: net.vaultcraft.vcbungee.VCBungee